services:
  losnotes:
    build: .
    container_name: losnotes
    depends_on:
      losnotes-postgresql:
        condition: service_healthy
    ports:
      - "84:8080"
    networks:
      - losnotes_net

  losnotes-postgresql:
    image: postgres:15-alpine
    container_name: losnotes-postgresql
    restart: always
    volumes:
      - /var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=froth_area_jot_rendition_buckwheat_rematch
      - POSTGRES_DB=notes_db
    networks:
      - losnotes_net
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 6s
      # interval: 120s
      # timeout: 60s
      # start_period: 80s
      retries: 5

networks:
  losnotes_net:
    name: losnotes_net